---
- name: Check mysql_root_password
  assert:
    that:
      - mysql_root_password | length > 0
      - mysql_repl_password | length > 0
      - mysql_group_replication_name | length > 0
  run_once: True
  delegate_to: localhost

- name: Check mysql_innodb_cluster_password
  assert:
    that:
      - mysql_innodb_cluster_password | length > 0
  run_once: True
  delegate_to: localhost
  when:
    - mysql_cluster_type == 'mgr'
    - mysql_innodb_cluster_enable|bool
