---
- name: Verify that cluster status
  mysql_query:
    query: SELECT member_state FROM performance_schema.replication_group_members WHERE member_id=@@server_uuid
  register: _cluster_status

- name: Change master for channel
  mysql_replication:
    mode: changemaster
    master_user: repl
    master_password: "{{ mysql_repl_password }}"
    channel: group_replication_recovery
  when:
    - _cluster_status.rowcount[0]|int == 0

- name: Verify that the primary node status
  mysql_query:
    query: SELECT * FROM performance_schema.replication_group_members where member_role='PRIMARY'
  run_once: true
  register: mysql_mgr_primary_status
  when:
    - ('mysql_primary' in groups and inventory_hostname in groups['mysql_primary']) or ansible_play_hosts.index(inventory_hostname) == 0
  tags:
    - skip_ansible_lint

- name: Initializing MGR cluster
  mysql_query:
    query:
      - "SET GLOBAL group_replication_bootstrap_group=ON;"
      - "START GROUP_REPLICATION;"
      - "SET GLOBAL group_replication_bootstrap_group=OFF;"
  run_once: true
  when:
    - ('mysql_primary' in groups and inventory_hostname in groups['mysql_primary']) or ansible_play_hosts.index(inventory_hostname) == 0
    - mysql_mgr_primary_status.rowcount[0]|int == 0
  tags:
    - skip_ansible_lint

- name: Verify that the member nodes status
  mysql_query:
    query: SELECT member_state FROM performance_schema.replication_group_members where member_id=@@server_uuid
  register: mysql_mgr_member_status
  when:
    - ('mysql_secondary' in groups and inventory_hostname in groups['mysql_secondary']) or ansible_play_hosts.index(inventory_hostname) != 0
  tags:
    - skip_ansible_lint

- name: Startting MGR cluster member nodes
  mysql_query:
    query: "START GROUP_REPLICATION;"
  when:
    - ('mysql_secondary' in groups and inventory_hostname in groups['mysql_secondary']) or ansible_play_hosts.index(inventory_hostname) != 0
    - mysql_mgr_member_status.rowcount[0]|int == 0 or mysql_mgr_member_status.query_result[0][0].member_state != 'ONLINE'
  tags:
    - skip_ansible_lint

- name: Copy gr_member_routing_candidate_status.sql
  copy:
    src: gr_member_routing_candidate_status.sql
    dest: /tmp/gr_member_routing_candidate_status.sql
  run_once: true
  when:
    - mysql_proxysql_config|bool
    - ('mysql_primary' in groups and inventory_hostname in groups['mysql_primary']) or ansible_play_hosts.index(inventory_hostname) == 0
    - mysql_initialize_status is not skipped

- name: Create internal view sys.gr_member_routing_candidate_status for monitoring
  shell: /usr/local/mysql/bin/mysql -uroot -p'{{ mysql_root_password }}' --socket={{ mysql_socket }} < /tmp/gr_member_routing_candidate_status.sql
  no_log: yes
  run_once: true
  when:
    - mysql_proxysql_config|bool
    - ('mysql_primary' in groups and inventory_hostname in groups['mysql_primary']) or ansible_play_hosts.index(inventory_hostname) == 0
    - mysql_initialize_status is not skipped

- name: Create proxysql monitor account
  mysql_user:
    name: "{{ mysql_proxysql_monitor_username }}"
    password: "{{ mysql_proxysql_monitor_password }}"
    host: "%"
    priv: "sys.*:SELECT"
    state: present
  when:
    - mysql_proxysql_config|bool
    - ('mysql_primary' in groups and inventory_hostname in groups['mysql_primary']) or ansible_play_hosts.index(inventory_hostname) == 0

- name: Show Group Replication status
  mysql_query:
    query: SELECT * FROM performance_schema.replication_group_members
  run_once: True
