---
- name: Converge
  hosts: all
  any_errors_fatal: yes
  roles:
    - role: daixijun.mysql
      mysql_version: 8.0.20
      mysql_group_replication_single_primary_mode: true
      mysql_root_password: ieng8Taibonga6dair0j
      mysql_repl_password: Ad5sa7aer7eiN3goo2be
      mysql_group_replication_name: cdbdc06c-2023-4d20-9821-272f160ef4f6
      mysql_databases:
        - name: db1
      mysql_users:
        - name: monitor
          password: monitor
          priv: "sys.*:SELECT"
        - name: ic
          password: hai0AiV7chaig5pheo=Z
          priv: "*.*:ALL,GRANT"
          host: "%"
