---
- name: Converge
  hosts: all
  any_errors_fatal: yes
  roles:
    - role: daixijun.mysql
      mysql_version: 8.0.20
      mysql_group_replication_single_primary_mode: true
      mysql_databases:
        - name: db1
      mysql_users:
        - name: monitor
          password: monitor
          priv: "sys.*:SELECT"
        - name: ic
          password: hai0AiV7chaig5pheo=Z
          priv: "*.*:ALL,GRANT"
          host: "%"
