- name: Side Effect
  hosts: all
  gather_facts: False
  tasks:
    - name: Restart Primary
      community.general.mysql_query:
        query: "{{ item }}"
      loop:
        - STOP GROUP_REPLICATION
        - START GROUP_REPLICATION
      when:
        - "(mysql_inventory_group+'_primary' in groups and inventory_hostname in groups[mysql_inventory_group+'_primary']) or groups[mysql_inventory_group].index(inventory_hostname) == 0"
