- name: Side Effect
  hosts: all
  gather_facts: False
  tasks:
    - name: Restart Primary
      community.general.mysql_query:
        query:
          - STOP GROUP_REPLICATION
          - START GROUP_REPLICATION
      run_once: true
      when:
        - groups['mysql'].index(inventory_hostname) == 0
