---
- name: Verify
  hosts: all
  become: true
  gather_facts: True
  any_errors_fatal: yes
  tasks:
    - name: Gather service facts
      service_facts:
      no_log: yes

    - name: Assert that the service state is running
      assert:
        that:
          - ansible_facts.services["mysqld"].state == "running"
          - ansible_facts.services["mysqld"].status == "enabled"

    - name: Stat socket file
      stat:
        path: /var/run/mysqld/mysqld.sock
        get_checksum: no
      register: socket_stat
      no_log: yes

    - name: Assert that the socket file is in the expected state
      assert:
        that:
          - socket_stat.stat.exists
          - socket_stat.stat.issock
          - socket_stat.stat.mode == "0777"
          - socket_stat.stat.pw_name == "mysql"
          - socket_stat.stat.gr_name == "mysql"

    - name: Gathers information about MySQL servers
      community.general.mysql_info:
        filter:
          - users
      no_log: True
      register: _info

    - name: Assert that users
      assert:
        that:
          - "'monitor' in _info.users['%']"
          - "'ic' in _info.users['%']"
          - "'user1' in _info.users['%']"

    - name: Show databases
      community.general.mysql_query:
        query: SHOW DATABASES
      register: _res
      vars:
        database:
          Database: db1
      failed_when: database not in _res.query_result[0]

    - name: Query replication group members
      community.general.mysql_query:
        query: SELECT * FROM performance_schema.replication_group_members WHERE MEMBER_STATE = 'ONLINE'
      register: _mgr_res
      failed_when: _mgr_res.rowcount[0] != groups[mysql_inventory_group] | length
